app:
  name: "BTCFeed.org"
  domain: "btcfeed.org"
  subdomain: "app"
render_protect: false
ssl:
  enabled: true    # Make sure to enable during deployment
  email: "support@btcfeed.org"
images:
  peatio: quay.io/openware/peatio:2.4.0-13aaf09
  barong: quay.io/openware/barong:2.4.0-20aee6e
  frontend: quay.io/openware/baseapp:2.4.0-045fdd5 # Check on quay.io/openware/baseapp for latest tags
  tower: quay.io/openware/tower:2.4.0-fec32c9
  postmaster: quay.io/openware/postmaster:2.3.5
arke_proxy:
  enabled: false
vendor:
  frontend: git@github.com:openware/baseapp.git
vault:
  mode: production
  token: changeme
storage:
  provider: "Google"
  bucketName: "opendax-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "v3"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "changeme"
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    max_balance: 1000.0
    secret: changeme
terraform:
  credentials: "~/safe/opendax.json"
  project: "example-opendax"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "opendax-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"

